[package]
description = "Nintendo 3DS project template"
name = "rust3ds-template"
version = "0.1.0"

[dependencies]
ctru-rs = { git = "https://github.com/panicbit/ctru-rs", branch = "nightly_update" }

[profile.dev]
panic = 'abort'

[profile.release]
lto = true
panic = 'abort'
