[package]
description = "Nintendo 3DS project template"
name = "rust3ds-template"
version = "0.1.0"
build = "build.rs"

[dependencies]
ctru-rs = { git = "https://github.com/rust3ds/ctru-rs", rev = "123d53f" }

[profile.dev]
panic = 'abort'

[profile.release]
lto = true
panic = 'abort'
